project:
  type: website
  output-dir: ../docs

website:
  title: "Making Cognitive Neuroscience Open and Reproducible"
  navbar:
    left:
      - href: http://poldrack.github.io/talks-MakingCogNeuroOpenReproducible
        text: Github page

format:
  html:
    theme: flatly
    css: styles.css

